### ISSUE TITLE
How do you use this? 

### ISSUE THREAD

**Issue by GonzaloCalandria** [ankur-rajput/google-oauth2-aem#1]
Hello! I'm trying to implement this on my project but I don't understand how to use this.
Do you have some tutorial for this?

**Comment by ankur-rajput** [comment]
This is an old repo. I can update the code and provide a tutorial doc as
well on this weekend if you can wait until then.

**Comment by GonzaloCalandria** [comment]
@ankur-rajput that would be awesome! Just FYI, I'm using aem  6.5

**Comment by ankur-rajput** [comment]
@GonzaloCalandria I found another repo with a detailed doc, please refer https://github.com/thegreyteacher/aem-social-login. I have gone through it and it looks good to me. Also, it says that it's tested on AEM 6.5.
Thanks

**Comment by GonzaloCalandria** [comment]
Thank you for that! I'll take a look
